
cut_point:
  desc: specify the model cut point
  value: !!int 2
sl_lr:
  desc: split learning rate
  value: !!float 0.25 # 0.25
adv_lr:
  desc: adversarial learning rate
  value: !!float 0.25
percent:
  desc: proportion of data set used for training
  value: !!float 0.25
batch_size:
  desc: batch size
  value: !!int 64
global_round:
  desc: global training round
  value: !!int 100
local_epoch:
  desc: local iteration epoch
  value: !!int 2
add_disc:
  desc: use discriminator or not
  value: !!bool True
k:
  desc: discriminator update round
  value: !!float 0.25
target_domain:
  desc: target domain (select a client as target domain, and the number here indicate client index)
  value: !!int 0
ratio_disc:
  desc: weight of gradient back propagated from discriminator
  value: !!float 1
