
model_type:
  desc: Specify the model to be trained
  value: !!str lenet # resnet18 or vgg16 or alexnet or lenet
disc_type:
  desc: Specify the type of discriminator, whether it is multi-classifier or anchor or no discriminator
  value: !!str anchor # mul or anchor or none
disc_mode:
  desc: set how discriminator works
  value: !!str gr # gr or normal
aggregate:
  desc: aggregate or not
  value: !!bool False
cut_point:
  desc: specify the model cut point
  value: !!int 3
sl_lr:
  desc: split learning rate
  value: !!float 0.1 # 0.25
adv_lr:
  desc: adversarial learning rate
  value: !!float 0.05
percent:
  desc: proportion of data set used for training
  value: !!float 1
batch_size:
  desc: batch size
  value: !!int 64
global_round:
  desc: global training round
  value: !!int 50
local_epoch:
  desc: local iteration epoch
  value: !!int 2
k:
  desc: discriminator update round
  value: !!float 0.25
target_domain:
  desc: target domain (select a client as target domain, and the number here indicate client index)
  value: !!int 0
ratio_disc:
  desc: weight of gradient back propagated from discriminator. Note that this parameter should be non-negative.
  value: !!float 40
