
dataset_name:
  desc: dataset name
  value: !!str office-home # domain-net or office-caltech10 or digits
  # value: !!str domain-net # domain-net or office-caltech10 or digits
  # value: !!str digits # domain-net or office-caltech10 or digits
domain:
  desc: domain name of each client (also control client num)
  value: [
      # "MNIST", "SVHN", "USPS", "SynthDigits", "MNIST_M", ## 原数据集
      # "MNIST-blur", "SVHN-blur", "USPS-blur", "SynthDigits-blur", "MNIST_M-blur", ## 高斯模糊后的数据集（高斯核随机选择为1，3，5，7）
      # "MNIST-noise", "SVHN-noise", "USPS-noise", "SynthDigits-noise", "MNIST_M-noise", ## 添加了高斯白噪声后的数据集 (mean:0, std: 0.2)
      # "MNIST-bright", "SVHN-bright", "USPS-bright", "SynthDigits-bright", "MNIST_M-bright",  ## 随机调整了亮度的数据集
      # "caltech", "dslr", "webcam", "amazon", ## office-caltech10
      # "caltech-blur", "dslr-blur", "webcam-blur", "amazon-blur", ## office-caltech10
      # "caltech-noise", "dslr-noise", "webcam-noise", "amazon-noise", ## office-caltech10
      # "caltech-bright", "dslr-bright", "webcam-bright", "amazon-bright", ## office-caltech10
      # "clipart", "real", "sketch", "quickdraw", "infograph", "painting", ## domain-net

      "Art", "Clipart", "Product", "RealWorld",
      "Art-blur", "Clipart-blur", "Product-blur", "RealWorld-blur",
      "Art-noise", "Clipart-noise", "Product-noise", "RealWorld-noise",
      "Art-bright", "Clipart-bright", "Product-bright", "RealWorld-bright",
    ]
model_type:
  desc: Specify the model to be trained
  value: !!str resnet18 # resnet18 or vgg16 or alexnet or lenet
disc_type:
  desc: Specify the type of discriminator, whether it is multi-classifier or anchor or no discriminator
  value: !!str anchor # mul or anchor or none
disc_mode:
  desc: set how discriminator works
  value: !!str gr # gr or normal
aggregate:
  desc: aggregate or not
  value: !!bool False
cut_point:
  desc: specify the model cut point
  value: !!int 4
sl_lr:
  desc: split learning rate
  value: !!float 0.01 # 0.25
adv_lr:
  desc: adversarial learning rate
  value: !!float 0.01
percent:
  desc: proportion of data set used for training
  value: !!float 1
batch_size:
  desc: batch size
  value: !!int 32
global_round:
  desc: global training round
  value: !!int 10
local_epoch:
  desc: local iteration epoch
  value: !!int 2
k:
  desc: discriminator update round
  value: !!float 0.25
target_domain:
  desc: target domain (select a client as target domain, and the number here indicate client index)
  value: !!int 0
ratio_disc:
  desc: weight of gradient back propagated from discriminator. Note that this parameter should be non-negative.
  value: !!float 25
test_freq:
  desc: test frequency
  value: !!int 50
