
cut_point:
  desc: specify the model cut point
  value: !!int 2
lr:
  desc: learning rate
  value: !!float 0.001 # 0.25
percent:
  desc: proportion of data set used for training
  value: !!float 0.25
batch_size:
  desc: batch size
  value: !!int 64
global_round:
  desc: global training round
  value: !!int 100
local_epoch:
  desc: local iteration epoch
  value: !!int 2
add_gan:
  desc: use discriminator or not
  value: !!bool True
k:
  desc: discriminator update round
  value: !!float 0.25
target_domain:
  desc: target domain (select a client as target domain, and the number here indicate client index)
  value: !!int 0
ratio_gan:
  desc: weight of gradient back propagated from discriminator
  value: !!float -1
